// Array para Bicicletas

const bicicletas = [
    {
        id: 1,
        nombre: "Road Monster",
        tipo: "Bicicleta de carretera",
        precio: 150,
        img: "img/Bicicletas/bike1.jpg",
        cantidad: 1,
        rodados: ['22', '24', '28'],
    },
    {
        id: 2,
        nombre: "CarbonX",
        tipo: "Bicicleta de carretera",
        precio: 200,
        img: "img/Bicicletas/bike2.jpg",
        cantidad: 1,
        rodados: ['20', '24', '26'],
    },
    {
        id: 3,
        nombre: "Speed Rider Pro",
        tipo: "Bicicleta de carretera",
        precio: 180,
        img: "img/Bicicletas/bike3.jpg",
        cantidad: 1,
        rodados: ['20', '22', '24'],
    },
    {
        id: 4,
        nombre: "Violet Storm",
        tipo: "Bicicleta de carretera",
        precio: 200,
        img: "img/Bicicletas/bike4.jpg",
        cantidad: 1,
        rodados: ['20', '26', '28'],
    },
    {
        id: 5,
        nombre: "Thunderbolt",
        tipo: "Bicicleta de montaña",
        precio: 250,
        img: "img/Bicicletas/bike5.jpg",
        cantidad: 1,
        rodados: ['22', '26', '28'],
    },
    {
        id: 6,
        nombre: "Trailblazer",
        tipo: "Bicicleta de montaña",
        precio: 300,
        img: "img/Bicicletas/bike6.jpg",
        cantidad: 1,
        rodados: ['20', '22', '26'],
    },
    {
        id: 7,
        nombre: "Wild Trail Blazer",
        tipo: "Bicicleta de montaña",
        precio: 250,
        img: "img/Bicicletas/bike7.jpg",
        cantidad: 1,
        rodados: ['22', '24', '28'],
    },
    {
        id: 8,
        nombre: "Summit Seeker Pro",
        tipo: "Bicicleta de montaña",
        precio: 300,
        img: "img/Bicicletas/bike8.jpg",
        cantidad: 1,
        rodados: ['20', '22', '24'],
    },
    {
        id: 9,
        nombre: "Kidd Cruiser",
        tipo: "Bicicleta de niños",
        precio: 50,
        img: "img/Bicicletas/bike9.jpg",
        cantidad: 1,
        rodados: ['12', '14', '16'],
    },
    {
        id: 10,
        nombre: "Mini Adventure Rider",
        tipo: "Bicicleta de niños",
        precio: 70,
        img: "img/Bicicletas/bike10.jpg",
        cantidad: 1,
        rodados: ['10', '12', '14'],
    },
    {
        id: 11,
        nombre: "Tiny Trekker Explorer",
        tipo: "Bicicleta de niños",
        precio: 80,
        img: "img/Bicicletas/bike11.jpg",
        cantidad: 1,
        rodados: ['10', '12', '14'],
    },
    {
        id: 12,
        nombre: "Little Speedster Pro",
        tipo: "Bicicleta de niños",
        precio: 75,
        img: "img/Bicicletas/bike12.jpg",
        cantidad: 1,
        rodados: ['12', '14', '18'],
    },
];

// Array Para Cascos

const cascos = [
    {   
        id: {
            id1: 13.1,
            id2: 13.2,
            id3: 13.3,
        },
        nombre: "Road Master Elite",
        tipo: "Casco de carretera",
        precio: 100,
        img: {
            img1 : "img/Cascos/casco1.1.jpg",
            img2 : "img/Cascos/casco1.2.jpg",
            img3 : "img/Cascos/casco1.3.jpg",
        },
        descripcion: "El casco Road Master Elite es la elección definitiva para los amantes de la carretera. Ofreciendo una combinación perfecta de estilo, seguridad y comodidad, este casco de primera categoría garantiza una experiencia de conducción inigualable.",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 14.1,
            id2: 14.2,
            id3: 14.3,
        },
        nombre: "Aero Shield Pro",
        tipo: "Casco de carretera",
        precio: 90,
        img: {
            img1 : "img/Cascos/casco2.1.jpg",
            img2 : "img/Cascos/casco2.2.jpg",
            img3 : "img/Cascos/casco2.3.jpg",
        },
        descripcion: "",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 15.1,
            id2: 15.2,
            id3: 15.3,
        },
        nombre: "Trail Guard Extreme",
        tipo: "Casco de carretera",
        precio: 150,
        img: {
            img1 : "img/Cascos/casco3.1.jpg",
            img2 : "img/Cascos/casco3.2.jpg",
            img3 : "img/Cascos/casco3.3.jpg",
        },
        descripcion: "El casco Trail Guard Extreme es la elección definitiva para los entusiastas del ciclismo de montaña que buscan aventuras sin límites. Diseñado para resistir los terrenos más desafiantes, este casco ofrece una combinación perfecta de protección y comodidad.",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 16.1,
            id2: 16.2,
            id3: 16.3,
        },
        nombre: "Aero Racer",
        tipo: "Casco de carretera",
        precio: 108,
        img: {
            img1 : "img/Cascos/casco4.1.jpg",
            img2 : "img/Cascos/casco4.2.jpg",
            img3 : "img/Cascos/casco4.3.jpg",
        },
        descripcion: "",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 17.1,
            id2: 17.2,
            id3: 17.3,
        },
        nombre: "Trail Guard Extreme",
        tipo: "Casco de montaña",
        precio: 200,
        img: {
            img1 : "img/Cascos/casco5.1.jpg",
            img2 : "img/Cascos/casco5.2.jpg",
            img3 : "img/Cascos/casco5.3.jpg",
        },
        descripcion: "El casco Trail Guard Extreme es la elección definitiva para los entusiastas del ciclismo de montaña que buscan aventuras sin límites. Diseñado para resistir los terrenos más desafiantes, este casco ofrece una combinación perfecta de protección y comodidad.",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 18.1,
            id2: 18.2,
            id3: 18.3,
        },
        nombre: "Cascadia Trail",
        tipo: "Casco de montaña",
        precio: 100,
        img: {
            img1 : "img/Cascos/casco6.1.jpg",
            img2 : "img/Cascos/casco6.2.jpg",
            img3 : "img/Cascos/casco6.3.jpg",
        },
        descripcion: "",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 19.1,
            id2: 19.2,
            id3: 19.3,
        },
        nombre: "Extreme Venture",
        tipo: "Casco de montaña",
        precio: 95,
        img: {
            img1 : "img/Cascos/casco7.1.jpg",
            img2 : "img/Cascos/casco7.2.jpg",
            img3 : "img/Cascos/casco7.3.jpg",
        },
        descripcion: "",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 20.1,
            id2: 20.2,
            id3: 20.3,
        },
        nombre: "Rock Hopper",
        tipo: "Casco de montaña",
        precio: 92,
        img: {
            img1 : "img/Cascos/casco8.1.jpg",
            img2 : "img/Cascos/casco8.2.jpg",
            img3 : "img/Cascos/casco8.3.jpg",
        },
        descripcion: "",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 21.1,
            id2: 21.2,
            id3: 21.3,
        },
        nombre: "Mini Adventur",
        tipo: "Casco de carretera",
        precio: 70,
        img: {
            img1 : "img/Cascos/casco9.1.jpg",
            img2 : "img/Cascos/casco9.2.jpg",
            img3 : "img/Cascos/casco9.3.jpg",
        },
        descripcion: "El casco MiniAdventura Kids es el compañero perfecto para las emocionantes travesías de los más pequeños. Diseñado pensando en la seguridad y la diversión, este casco ofrece la protección esencial que tus hijos necesitan mientras exploran el mundo en sus bicicletas.",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 22.1,
            id2: 22.2,
            id3: 22.3,
        },
        nombre: "Kid Safe",
        tipo: "Casco para niños",
        precio: 35,
        img: {
            img1 : "img/Cascos/casco10.1.jpg",
            img2 : "img/Cascos/casco10.2.jpg",
            img3 : "img/Cascos/casco10.3.jpg",
        },
        descripcion: "",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 23.1,
            id2: 23.2,
            id3: 23.3,
        },
        nombre: "Fun Ride Junior",
        tipo: "Casco para niños",
        precio: 32,
        img: {
            img1 : "img/Cascos/casco11.1.jpg",
            img2 : "img/Cascos/casco11.2.jpg",
            img3 : "img/Cascos/casco11.3.jpg",
        },
        descripcion: "",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 24.1,
            id2: 24.2,
            id3: 24.3,
        },
        nombre: "Star Strider",
        tipo: "Casco para niños",
        precio: 28,
        img: {
            img1 : "img/Cascos/casco12.1.jpg",
            img2 : "img/Cascos/casco12.2.jpg",
            img3 : "img/Cascos/casco12.3.jpg",
        },
        descripcion: "",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
];

// Array Para Accesorios

const accesorios = [
    {
        id: {
            id1: 25.1,
            id2: 25.2,
            id3: 25.3,
        },
        nombre: "Comfort Fit",
        tipo: "Camiseta para Hombre",
        precio: 10,
        img: {
            img1 : "img/Accesorios/camiseta1.1.png",
            img2 : "img/Accesorios/camiseta1.2.png",
            img3 : "img/Accesorios/camiseta1.3.png",
        },
        descripcion: "La Camiseta Comfort Fit para hombre es la elección perfecta para quienes buscan comodidad y estilo en una sola prenda. Su ajuste holgado y tejido suave te brindarán una sensación de máxima comodidad durante todo el día, mientras que su diseño versátil se adapta a cualquier ocasión.",
        cantidad: 1,
        colores: ['', '', ''],
    },
    {
        id: {
            id1: 26.1,
            id2: 26.2,
            id3: 26.3,
        },
        nombre: "Elegance Essence",
        tipo: "Camiseta para Mujer",
        precio: 10,
        img: {
            img1 : "img/Accesorios/camiseta2.1.png",
            img2 : "img/Accesorios/camiseta2.2.png",
            img3 : "img/Accesorios/camiseta2.3.png",
        },
        descripcion: "",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 27.1,
            id2: 27.2,
            id3: 27.3,
        },
        nombre: "Urban Chic",
        tipo: "Camiseta para Niño",
        precio: 7,
        img: {
            img1 : "img/Accesorios/camiseta3.1.png",
            img2 : "img/Accesorios/camiseta3.2.png",
            img3 : "img/Accesorios/camiseta3.3.png",
        },
        descripcion: "",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 28.1,
            id2: 28.2,
            id3: 28.3,
        },
        nombre: "Little Star",
        tipo: "Camiseta para Niña",
        precio: 7,
        img: {
            img1 : "img/Accesorios/camiseta4.1.png",
            img2 : "img/Accesorios/camiseta4.2.png",
            img3 : "img/Accesorios/camiseta4.3.png",
        },
        descripcion: "",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 29.1,
            id2: 29.2,
            id3: 29.3,
        },
        nombre: "Urban Comfort",
        tipo: "Canguro para Hombre",
        precio: 22,
        img: {
            img1 : "img/Accesorios/camiseta5.1.png",
            img2 : "img/Accesorios/camiseta5.2.png",
            img3 : "img/Accesorios/camiseta5.3.png",
        },
        descripcion: "El canguro Comfort para hombre es la prenda esencial para un estilo relajado y a la moda. Diseñada con atención a los detalles y confeccionada con un suave y cálido tejido, esta sudadera te brinda comodidad inigualable y un aspecto moderno. Ya sea que la uses para tus aventuras urbanas diarias o para relajarte en casa, la Urban Comfort es la elección perfecta.",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 30.1,
            id2: 30.2,
            id3: 30.3,
        },
        nombre: "Elegance Cozy",
        tipo: "Canguro para Mujer",
        precio: 22,
        img: {
            img1 : "img/Accesorios/camiseta6.1.png",
            img2 : "img/Accesorios/camiseta6.2.png",
            img3 : "img/Accesorios/camiseta6.3.png",
        },
        descripcion: "El canguro Elegance Cozy para mujer es la combinación perfecta de estilo y comodidad. Confeccionada con suave y cálido material que te mantendrá abrigada en cualquier temporada, esta sudadera te brinda un toque de elegancia y una sensación de acogedora comodidad. Su diseño moderno y femenino se adapta a tu estilo personal, ya sea para una salida casual o una tarde de relajación en casa.",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 31.1,
            id2: 31.2,
            id3: 31.3,
        },
        nombre: "Active Kid",
        tipo: "Canguro para Niño",
        precio: 15,
        img: {
            img1 : "img/Accesorios/camiseta7.1.png",
            img2 : "img/Accesorios/camiseta7.2.png",
            img3 : "img/Accesorios/camiseta7.3.png",
        },
        descripcion: "",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    },
    {
        id: {
            id1: 32.1,
            id2: 32.2,
            id3: 32.3,
        },
        nombre: "Sweet Heart",
        tipo: "Canguro para Niña",
        precio: 15,
        img: {
            img1 : "img/Accesorios/camiseta8.1.png",
            img2 : "img/Accesorios/camiseta8.2.png",
            img3 : "img/Accesorios/camiseta8.3.png",
        },
        descripcion: "El canguro Sweet Heart para niña es la prenda perfecta para mantener a tu pequeña abrigada y con estilo en cualquier ocasión. Con su diseño encantador y detalles cuidadosamente elegidos, esta sudadera combina comodidad y moda de manera excepcional. El tejido suave y cálido garantiza que tu hija esté cómoda en cualquier temporada, ya sea para jugar al aire libre o relajarse en casa.",
        cantidad: 1,
        colores: [' ', ' ', ' '],
    }
];

// Creo el carrito
let carrito = JSON.parse(localStorage.getItem("carrito")) || [];

